<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.scijava</groupId>
		<artifactId>pom-scijava</artifactId>
		<version>45.1.0</version>
		<relativePath />
	</parent>

	<groupId>fiji.plugin</groupId>
	<artifactId>fiji-appose</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>Fiji Appose</name>
	<description>Collection of utilities to facilitate writing Appose plugins
		for Fiji</description>
	<url>https://fiji.sc/</url>
	<inceptionYear>2028</inceptionYear>
	<organization>
		<name>Fiji</name>
		<url>https://fiji.sc/</url>
	</organization>
	<licenses>
		<license>
			<name>Simplified BSD License</name>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>tinevez</id>
			<name>Jean-Yves Tinevez</name>
			<url>https://imagej.net/people/tinevez</url>
			<roles>
				<role>lead</role>
				<role>developer</role>
				<role>debugger</role>
				<role>reviewer</role>
				<role>support</role>
				<role>maintainer</role>
			</roles>
		</developer>
	</developers>
	<contributors>
		<contributor>
			<name>none</name>
		</contributor>
	</contributors>

	<mailingLists>
		<mailingList>
			<name>Image.sc Forum</name>
			<archive>https://forum.image.sc/tag/fiji</archive>
		</mailingList>
	</mailingLists>

	<scm>
		<connection>scm:git:https://github.com/fiji/fiji-appose</connection>
		<developerConnection>scm:git:git@github.com:fiji/fiji-appose</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/fiji/fiji-appose</url>
	</scm>
	<issueManagement>
		<system>GitHub Issues</system>
		<url>https://github.com/fiji/fiji-appose/issues</url>
	</issueManagement>
	<ciManagement>
		<system>GitHub Actions</system>
		<url>https://github.com/fiji/fiji-appose/actions</url>
	</ciManagement>

	<properties>
		<package-name>fiji.plugin.appose</package-name>

		<license.copyrightOwners>Fiji developers.</license.copyrightOwners>
		<license.projectName>Fiji distribution of ImageJ for the life sciences.</license.projectName>

		<!-- NB: Deploy releases to the SciJava Maven repository. -->
		<releaseProfiles>sign,deploy-to-scijava</releaseProfiles>

		<scijava.jvm.version>21</scijava.jvm.version>
		<scijava.jvm.build.version>[21,)</scijava.jvm.build.version>

		<appose.version>0.12.0</appose.version>
		<imglib2-appose.version>0.10.0-SNAPSHOT</imglib2-appose.version>
	</properties>

	<repositories>
		<!-- NB: for SciJava dependencies -->
		<repository>
			<id>scijava.public</id>
			<url>https://maven.scijava.org/content/groups/public</url>
		</repository>
	</repositories>

	<dependencies>
		<!-- Fiji Is Just ImageJ! -->
		<dependency>
			<groupId>net.imagej</groupId>
			<artifactId>imagej</artifactId>
		</dependency>
		<dependency>
			<groupId>net.imagej</groupId>
			<artifactId>ij</artifactId>
		</dependency>
		<dependency>
			<groupId>net.imagej</groupId>
			<artifactId>ij1-patcher</artifactId>
		</dependency>
		<dependency>
			<groupId>net.imagej</groupId>
			<artifactId>imagej-legacy</artifactId>
		</dependency>

		<!-- Config-UI -->
		<dependency>
			<groupId>org.scijava</groupId>
			<artifactId>config-ui</artifactId>
			<version>0.0.7</version>
		</dependency>

		<!-- Appose dependencies -->
		<dependency>
			<groupId>org.apposed</groupId>
			<artifactId>appose</artifactId>
			<version>${appose.version}</version>
		</dependency>
		<!-- We have to temporary depend on imglib2-appose, 
		because this is the repo where some core interfaces are, 
		waiting to be moved upstream in appose. -->
		<dependency>
			<groupId>net.imglib2</groupId>
			<artifactId>imglib2-appose</artifactId>
			<version>${imglib2-appose.version}</version>
		</dependency>
	</dependencies>
</project>
